apiVersion: v1
kind: Service
metadata:
  name: tomcat-server-service
  labels:
    name: tomcat-servcer-service
    app: tomcat-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: tomcat-server
