services:
  web:
    image: hankaji/tc:latest
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
